wandb:
  project: eglinton_bus
  name: PPGEO_pretrained__run3  # fixed to avoid ${model.name} error
  sync_tensorboard: True
  log_dir: logs
  mode: online

model:
  use_ppgeo_pretrained_encoder: False
  freeze_encoder: False
  rgb_input: False
  name: ResNet34PilotNet
  pretrained: False
  trainable: True
  training: True
  compile:
    loss: ['mae', 'mae']
    optimizer:
      type: Adam
      learning_rate: 1e-5
    loss_weights: [1, 1]
    metrics: ['mae', 'mae']

training:
  cmd_list: ["cmd_0"]
  epochs: 10
  batch_size: 4
  random_seed: 42
  shuffle: True
  load_checkpoint: False
  save_model_dir: "saved_models_logs"
  checkpoint_lr: 0
  train_ratio: 0.8
  valid_ratio: 0.2
  train_coeff: 0.3
  valid_coeff: 0.3
  test_coeff: 1
  callbacks:
    - type: ModelCheckpoint
      filepath: ResNet34PilotNet.pt  # fixed extension
      monitor: val_loss
      mode: min
      save_best_only: True
      save_freq: epoch
      verbose: 0
    - type: EarlyStopping
      monitor: val_loss
      mode: min
      patience: 3
      verbose: 0
    - type: ReduceLROnPlateau
      monitor: val_loss
      factor: 0.5
      patience: 1
      min_lr: 5e-7
      verbose: 2
    - type: TensorBoard
      log_dir: logs
      histogram_freq: 1
      update_freq: epoch
      write_graph: True
      write_images: True

dataset:
  sorted_data_path: "/media/sim/data/eglinton_datasorting_dual/sorted_eglinton_data"  # fixed path
  shuffle: True
  dataset_mapping:
    0: "CIL_Dual_Cam_Stage1"
    1: "CIL_Dual_Cam_Stage2"
    2: "CIL_Dual_Cam_Stage2_B"
    3: "three_roundabouts_front_cam_only"
    4: "CIL_Dual_Cam_Stage2_First_Half"
    5: "CIL_Dual_Cam_Stage2_Second_Half"
  dataset_idx_list: [2, 3, 4, 5]  # corrected

  behavior_lists:
    main:
      list:
        - "lane_following"
    cmd_0:
      main_div: 1
      branch_multi: 1
      list:
        - "lane_bay_pass"
        - "roundabout_straight"
        - "intersection_lane_following"
        - "startpoint_out"
        - "startpoint_in"
        - "carpark_pass"
        - "roundabout_right_turn"
        - "lane_empty_bay"
        - "lane_empty_bay_first_half"
        - "lane_empty_bay_second_half"
        - "pullout"
    cmd_1:
      main_div: 10
      branch_multi: 1
      list:
        - "pullin"
        - "roundabout_turn_around_to_office"
        - "intersection_turn_around_to_office"
        - "startpoint_out"
        - "startpoint_in"
        - "carpark_entry"
        - "roundabout_right_turn"
        - "pullin_stops"
        - "carpark_left_turn_in"
        - "carpark_left_turn_out"
    cmd_2:
      main_div: 10
      branch_multi: 1
      list:
        - "reverse"
        - "roundabout_turn_around_to_beach"
        - "intersection_turn_around_to_beach"
        - "startpoint_out"
        - "startpoint_in"
        - "carpark_entry"
        - "roundabout_right_turn"
        - "pullout_stops"
        - "reverse_manual"
        - "carpark_left_turn_in"
        - "carpark_left_turn_out"
    cmd_3:
      main_div: 10
      branch_multi: 1
      list:
        - "carpark_dualsteering"
        - "cul_de_sac_dualsteering"

augmentation:
  augment_data: True
  augment_prob: 0.05
  horizontal_flip: False
  add_blur: True
  blur_range: 5
  add_noise: True
  noise_range: 0.02
  adjust_brightness: False
  brightness_range: 0.05
  add_shadow: True
  shadow_range: 0.1
  horizontal_shift: True
  steering_shift_factor: 0.2
  horizontal_rotate: False
  steering_rotate_factor: 0.2

